### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by 132ikl** [Howaner/NBTEditor#1]
Hello, I am interested in possibly making modifications to this application and Pull Requesting it, but unfortunately it does not have a license. Because of this, by default it is "All Rights Reserved" which details that no changes can be made to the software. I would appreciate if you would add a license file so that people can make changes whether locally or shared. If you don't know much about licenses, this is a good tool to help you get started:
https://choosealicense.com/

Thanks

**Comment by Howaner** [comment]
Hello 132ikl,

I'm sorry that I read your issue so late.
I added the BSD 3 License file to the project.

Best regards,
Howaner

**Comment by 132ikl** [comment]
Thanks :)
